### ISSUE TITLE
Relational  data Filter not working

### ISSUE THREAD

**Issue by anupamsomani15** [softlayer/softlayer-go#103]
service := services.GetAccountService(sess)

	mask := "mask[podName,account[id],datacenter[name]]"
	filter := filter.Build(
		filter.Path("subnets.podName").Eq(s.PodName),
	)
	service = service.Mask(mask).Filter(filter)
	// Call method getSubnets() in order to get all subnets in the Account.
	subnets, err := service.GetPrivateSubnets()

For reference :
https://stackoverflow.com/questions/50494815/softlayer-user-customergetobject-softlayer-failed-with-exception

**Comment by acamacho82** [comment]
This isn't a softlayer-go issue, it should be reported to SoftLayer by opening a ticket. Take in count that not all relational properties will work when using filters, specially those ones which don't belong to any object or datatype.

I can suggest you to use the **primaryRouter.hostname** instead of podName, the filter is something like below:

```
{"privateSubnets":{"datacenter":{"name":{"operation":"dal09"}},"networkVlan":{"primaryRouter":{"hostname":{"operation":"^= bcr06"}}}}}
```
**bcr06** means that the subnet has conection through the backend network (private) of **pod06**

The response is something like below:
```
               "datacenter": {
			"name": "dal09"
		},
		"networkVlan": {
			"id": 111333322,
			"modifyDate": "2016-09-14T13:24:10-04:00",
			"primarySubnetId": 1225544,
			"vlanNumber": 111,
			"primaryRouter": {
				"domain": "softlayer.com",
				"fullyQualifiedDomainName": "bcr06a.dal09.softlayer.com",
			}
		},
		"podName": "dal09.pod06"
```

**Comment by anupamsomani15** [comment]
But how to get the value of "bcr06" If I have only podname and datacenter name. ?
