### ISSUE TITLE
setUserMetadata is not implemented

### ISSUE THREAD

**Issue by YouHang** [softlayer/softlayer-go#115]
when creating new instances with user metadata:

SoftLayer_Exception_NotImplemented: SoftLayer_Virtual_Guest_Strategy_Behavior_Standard::setUserMetadata is not implemented. (HTTP 500)

#https://github.com/IBM-Cloud/ibm-cloud-cli-release/issues/44

**Comment by acamacho82** [comment]
I'm not able to reproduce the error, I created the following piece of code based in official documentation for createObject method https://softlayer.github.io/reference/services/SoftLayer_Virtual_Guest/createObject/ and I also tried by sending the same information (flavor, os, maxspeed, etc.) https://github.com/IBM-Cloud/ibm-cloud-cli-release/issues/44.

On `metadataValue` below, I put different values and all of them were successfully added to the vsi, the issue might be due to the information the user is trying to send through `userData.value`

```go
        virtualService := services.GetVirtualGuestService(sess)

	metadataValue := sl.String("<?xml version='1.0' encoding='UTF-8'?>" +
		"<note>" +
		"<to>Tove</to>" +
		"<from>Jani</from>" +
		"<heading>Reminder</heading>" +
		"<body>Don't forget me this weekend!</body>" +
		"</note>")

	objectTemplate := &datatypes.Virtual_Guest{
		Hostname: sl.String("node"),
		Domain:   sl.String("mydomain.com"),
		Datacenter: &datatypes.Location{
			Name: sl.String("syd04"),
		},
		SupplementalCreateObjectOptions: &datatypes.Virtual_Guest_SupplementalCreateObjectOptions{
			FlavorKeyName: sl.String("B1_4X8X100"),
		},
		NetworkComponents: []datatypes.Virtual_Guest_Network_Component{
			{MaxSpeed: sl.Int(1000)},
		},
		HourlyBillingFlag:            sl.Bool(true),
		LocalDiskFlag:                sl.Bool(false),
		OperatingSystemReferenceCode: sl.String("CENTOS_7_64"),
		UserData: []datatypes.Virtual_Guest_Attribute{
			{Value: metadataValue},
		},
	}

        // HERE we are calling to createObject method
	guest, err := virtualService.Mask("id;userData;hostname;domain").CreateObject(objectTemplate)
	
        if err != nil {
		fmt.Printf("\n Unable to create VSI with metadata:\n - %s\n", err)
		return
	}

	jsonFormat, jsonErr := json.Marshal(guest)
	if jsonErr != nil {
		fmt.Println(jsonErr)
		return
	}

	fmt.Println(string(jsonFormat))
```

**Comment by allmightyspiff** [comment]
`ibmcloud sl vs create ` calls createObject and THEN calls SL_Virtual_Guest::setUserMetadata immediately after.  After doing some research into this problem, I think it is caused by calling setUserMetadata on a guest that hasn't started provisioning yet. 

I think if the Softlayer-go library hits this error, it should try waiting and trying again a few times, that might help here.

**Comment by YouHang** [comment]
Thanks! @allmightyspiff @acamacho82, that should be the problem. It was fixed.
