### ISSUE TITLE
github.com/renier/xmlrpc is an unmaintained fork

### ISSUE THREAD

**Issue by onlyjob** [softlayer/softlayer-go#138]
For some strange reason _softlayer-go_ [uses](https://github.com/softlayer/softlayer-go/blob/master/session/xmlrpc.go#L28) unmaintained fork [github.com/renier/xmlrpc](https://github.com/renier/xmlrpc) instead of the original project - [github.com/kolo/xmlrpc](https://github.com/kolo/xmlrpc). The latter is better maintained and (unlike its fork) have issue tracker enabled.

Please consider using the original project.

**Comment by allmightyspiff** [comment]
The kolo project itself doesn't seem to be actively maintained either.  

https://github.com/kolo/xmlrpc#status: `This project is in minimal maintenance mode with no further development.`

@renier's version has a few features the kolo project doesn't that would make simply moving over a bit difficult. Like the XmlRpcError class, and supporting timeouts. I compared the two projects, and I personally don't see any real benefit to changing this dependency.  Ideally we'd get reneir's changes merged upstream so we can just use the original project, but I don't fell that I know enough about the library to know how much reneir's changes would break for other projects.

I do agree though that using a personal fork of a library might not be the best, might be a good idea to just add that library to a vendor folder or something of that nature since it is a small library.

**Comment by renier** [comment]
@allmightyspiff Correct. At the time the fork was created I pulled in fixes from other forks on kolo's repository that had not made it upstream, plus added my own.

At this point, it is better to worry about actual bugs. Feel free to use the issue tracker here for that. The intent is to support softlayer-go's needs with as little dependencies as possible and not necessarily to have a clean link back to a genral-purpose xmlrcp library. From that point of view, vendoring it makes a lot of sense. Open to anyone submitting the PR for that.

**Comment by onlyjob** [comment]
I would keep this issue open as it is an outstanding problem that needs to be solved sooner or later.
Believe it or not this is an actual bug because this _problem_ affects software life cycle and dependency hygiene. It is not a good idea to depend on dead/unmaintained code.

This is also a practical problem downstream (e.g. in Debian) where packaging unmaintained fork as a reusable library makes little sense.
