### ISSUE TITLE
Not able to get iops data

### ISSUE THREAD

**Issue by narkarum** [softlayer/softlayer-go#151]
Seems the iops is not being populated. Doc has the property but data is not being populated.

```

slcli -v  --format=json call-api SoftLayer_Account getNetworkStorage --limit=1000 --mask="mask[accountId;capacityGb;iops;createDate;id;username;notes;serviceResource.datacenter.name,guestId]" --json-filter='{"networkStorage":{"id":{"operation":138281016}}}'
Calling: SoftLayer_Account::getNetworkStorage(id=None, mask='mask[accountId;capacityGb;iops;createDate;id;guestId]', filter='{'networkStorage': {'id': {'operation': 138281016}}}', args=(), limit=1000, offset=None))
[
    {
        "accountId": 1920919,
        "capacityGb": 20,
        "createDate": "2020-04-28T04:56:09-05:00",
        "id": 138281016,
    }
]

```

**Comment by allmightyspiff** [comment]
1) SLCLI questions go to https://github.com/softlayer/softlayer-python/issues in the future.
2) If you are filtering based off an ID, just use a getObject call (SoftLayer_Network_Storage getObject in this case). Unless you were just filtering off that Id because your having problems with that specific volume, then ignore this.
3. [provisionediops](https://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_Storage/#provisionediops) is the value you are looking for.  [iops](https://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_Storage/#iops) only applies to PERFORMANCE block storage volumes, not endurance.

Hope that helps.
